vborder/MidtermProject

BruShr/src/main/webapp/WEB-INF/login.jsp
BruShr/src/main/webapp/WEB-INF/profile.jsp
BruShr/src/main/webapp/resources/styles.css

Added styles to Login and Profile

Added styles to Login and Profile

---

BruShr/src/main/webapp/WEB-INF/index.jsp
BruShr/src/main/webapp/WEB-INF/profile.jsp
BruShr/src/main/webapp/resources/styles.css

Index grid for beer recipe cards. styled profile page and styles.css

Index grid for beer recipe cards. styled profile page and styles.css

---

BruShr/src/main/webapp/WEB-INF/index.jsp
BruShr/src/main/webapp/WEB-INF/login.jsp

DB merge conflict branch

---

BruShr/src/main/java/com/skilldistillery/brushr/controllers/HomeController.java
BruShr/src/main/java/com/skilldistillery/brushr/data/BeerDAO.java
BruShr/src/main/java/com/skilldistillery/brushr/data/BeerDAOImpl.java
BruShr/src/main/webapp/WEB-INF/createbeer.jsp
JPABruShr/src/main/java/com/skilldistillery/brushr/entities/BeerRecipe.java
JPABruShr/src/main/java/com/skilldistillery/brushr/entities/User.java

Add beer methods complete

---

BruShr/src/main/webapp/WEB-INF/beerinfo.jsp
BruShr/src/main/webapp/WEB-INF/createuser.jsp
BruShr/src/main/webapp/WEB-INF/login.jsp
BruShr/src/main/webapp/resources/styles.css

connect styles to login, create user and beerinfo

connect styles to login, create user and beerinfo

---

BruShr/src/main/webapp/WEB-INF/footer.jsp
BruShr/src/main/webapp/resources/styles.css

Worked on NAv.jsp Footer.jsp and Styles .jsp

Worked on NAv.jsp Footer.jsp and Styles .jsp

---

BruShr/src/main/webapp/WEB-INF/beerinfo.jsp

Added skeleton to user comments

Db beerinfo.jsp

---

BruShr/src/main/java/com/skilldistillery/brushr/controllers/HomeController.java
BruShr/src/main/java/com/skilldistillery/brushr/data/BeerDAOImpl.java
BruShr/src/main/webapp/WEB-INF/beerinfo.jsp
DB/brushrdb.sql
JPABruShr/src/main/java/com/skilldistillery/brushr/entities/Comment.java

Comments added to beer

---

BruShr/src/main/webapp/WEB-INF/createuser.jsp
BruShr/src/main/webapp/WEB-INF/navbar.jsp

update navbar and had to update createuser.jsp to inlcude c tag library.

Navbarlogic

---

BruShr/src/main/java/com/skilldistillery/brushr/controllers/HomeController.java
BruShr/src/main/webapp/WEB-INF/beerinfo.jsp
BruShr/src/main/webapp/resources/styles.css

Added comment text area and persisting comments to beer info

Added comment text area and persisting comments to beer info

---

BruShr/src/main/webapp/WEB-INF/createuser.jsp

Create User additions

---

BruShr/src/main/webapp/WEB-INF/index.jsp

HOWDY Y'ALL, I MADE DEM DER SEARCHES!

added placeholder search bar to work on backend

---

BruShr/src/main/java/com/skilldistillery/brushr/controllers/HomeController.java
BruShr/src/main/java/com/skilldistillery/brushr/data/BeerDAOImpl.java
BruShr/src/main/webapp/WEB-INF/index.jsp

It's ALIVE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

added ability to search beers by name

---

BruShr/src/main/webapp/WEB-INF/index.jsp
BruShr/src/main/webapp/resources/styles.css

Carousel height work stash

---

BruShr/src/main/java/com/skilldistillery/brushr/controllers/HomeController.java
BruShr/src/main/java/com/skilldistillery/brushr/data/BeerDAOImpl.java

added routing for about page

---

BruShr/src/main/webapp/WEB-INF/about.jsp
BruShr/src/main/webapp/WEB-INF/fail.jsp
BruShr/src/main/webapp/WEB-INF/success.jsp

Team I the about page needs your profile links, image for your card if you don't like the one stubbed out, as well as a quick one-liner about you. Thx

Success fail about jsp

---

BruShr/src/main/webapp/WEB-INF/about.jsp
BruShr/src/main/webapp/WEB-INF/fail.jsp
BruShr/src/main/webapp/WEB-INF/navbar.jsp
BruShr/src/main/webapp/WEB-INF/success.jsp

update on about page, success and fail page cleared up od…d star, navbar removed the duplicate sign in and search feature

dev profile 

---

BruShr/src/main/webapp/WEB-INF/index.jsp
BruShr/src/main/webapp/resources/styles.css

Searchbar width hotfix

---

BruShr/src/main/webapp/WEB-INF/about.jsp

about.jsp required attention for typos

about.jsp required attention for typos

---

BruShr/src/main/webapp/WEB-INF/createuser.jsp
BruShr/src/main/webapp/WEB-INF/footer.jsp
BruShr/src/main/webapp/WEB-INF/login.jsp
BruShr/src/main/webapp/WEB-INF/navbar.jsp
BruShr/src/main/webapp/WEB-INF/profile.jsp
BruShr/src/main/webapp/resources/styles.css

Footer sizing, about link and fixed bottom fixes.  Fixed banner on create user

Footer sizing, about link and fixed bottom fixes.  Fixed banner on create user

---

BruShr/src/main/webapp/WEB-INF/profile.jsp

User can see list of their beers in profile

---

JPABruShr/src/main/java/com/skilldistillery/brushr/entities/BeerRecipe.java

The last added comment now shows up first in the comment list

reversed order of comments

---

BruShr/src/main/webapp/WEB-INF/beerinfo.jsp
BruShr/src/main/webapp/WEB-INF/createbeer.jsp
BruShr/src/main/webapp/WEB-INF/index.jsp

Added the default images for beer that don't have one and took the extra test info out of beer info

Quickfixes branch

---

BruShr/src/main/webapp/WEB-INF/beerinfo.jsp

redo of font fix for comments
